#!/bin/bash
if ! which npx > /dev/null
then
  echo "node is not installed on this machine."
  echo "Please install the most recent release of node below:"
  echo "https://nodejs.org/en/"
  exit 1
fi

if [ ! -d "./node_modules" ]; then
  echo "Installing dependencies..."
  npm ci
fi

npx ts-node . $@
