#!/bin/bash
if ! command -v npx &> /dev/null
then
  echo "node is not installed on this machine."
  echo "Please install the most recent release of node below:"
  echo "https://nodejs.org/en/"
  exit 1
fi

if ! command -v gcloud &> /dev/null
then
  echo "gcloud is not installed on this machine."
  echo "Please install the the google cloud cli here:"
  echo "https://cloud.google.com/sdk/gcloud?hl=de"
  exit 1
fi

if ! command -v git &> /dev/null
then
  echo "git is not installed on this machine."
  echo "Please install git here:"
  echo "https://git-scm.com/"
  exit 1
fi

if [ ! -d "./node_modules" ]; then
  echo "Installing dependencies..."
  npm ci
fi

npx ts-node . $@
